version: '3.7'
name: 'lightning-explorer'

services:
  webserver:
    image: nginx:1.25.1-perl
    restart: no
    volumes:
      - ./volumes/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./volumes/nginx/site-content:/etc/nginx/html
    ports:
      - '80:80'
      - '443:443'

  certbot:
    image: certbot/certbot:v2.6.0
    restart: no
    volumes:
      - ./volumes/certbot/etc:/etc/letsencrypt
      - ./volumes/certbot/var:/var/lib/letsencrypt
      - ./volumes/nginx/site-content:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email support@lightning.space --agree-tos --no-eff-email --force-renewal -d dev.explorer.lightning.space -d vm-lds-exp-dev.westeurope.cloudapp.azure.com
